service: crud-users-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs10.x
  environment: ${file(config/${self:custom.stage}.yml):environment} # pega a varivel de acordo com o ambiente

plugins:
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage, 'local'}

functions: ${file(src/services/users/endpoints/_functions.yml)}
